version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-test
    volumes:
      - kafka_data:/tmp/kraft-storage
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  perf_db:
    container_name: perf_db_container
    image: postgres:16
    environment:
      POSTGRES_USER: micro_admin
      POSTGRES_PASSWORD: micro_pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: perf_db
    volumes:
      - perf_db:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - kafka-test
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - perf_db
    environment:
      DB_HOST: perf_db
      DB_PORT: 5432
      DB_NAME: perf_db
      DB_USER: micro_admin
      DB_PASSWORD: micro_pass
    ports:
      - "8000:8000"
    networks:
      - kafka-test
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - kafka-test
    restart: unless-stopped

  logger_service:
    build:
      context: ./logger_service
      dockerfile: Dockerfile
    container_name: logger_service
    depends_on:
      - perf_db
      - kafka
    networks:
      - kafka-test
    environment:
      DB_HOST: perf_db
      DB_PORT: 5432
      DB_NAME: perf_db
      DB_USER: micro_admin
      DB_PASSWORD: micro_pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: training_data

  data_loader:
    build:
      context: ./src/data_loader
      dockerfile: dockerfile
    volumes:
      - ./data/datasets:/data/datasets
    networks:
      - ml_network

  pytorch:
    build:
      context: ./src/modeles_ia/pytorch
      dockerfile: dockerfile
    volumes:
      - ./data/datasets:/data/datasets:ro
    depends_on:
      data_loader:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3G
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: training_data
      EPOCHS: 2
      MAX_BATCHES_PER_EPOCH: 30
      METRIC_EVERY_N_BATCHES: 10
    networks:
      - ml_network
      - kafka-test

  tensorflow:
    build:
      context: ./src/modeles_ia/tensorflow
      dockerfile: dockerfile
    volumes:
      - ./data/datasets:/data/datasets:ro
    depends_on:
      data_loader:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3G
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: training_data
      EPOCHS: 2
      MAX_BATCHES_PER_EPOCH: 30
      METRIC_EVERY_N_BATCHES: 10
    networks:
      - ml_network
      - kafka-test

networks:
  kafka-test:
    driver: bridge
  ml_network:
    driver: bridge

volumes:
  perf_db:
  kafka_data:
