version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-test
    volumes:
      - kafka_data:/tmp/kraft-storage
    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  perf_db:
    container_name: perf_db_container
    image: postgres
    environment:
      POSTGRES_USER: micro_admin
      POSTGRES_PASSWORD: micro_pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: perf_db
    volumes:
      - perf_db:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - kafka-test
    restart: unless-stopped

  logger_service:
    build:
      context: ./logger_service
      dockerfile: Dockerfile
    container_name: logger_service
    depends_on:
      - perf_db
      - kafka
    volumes:
      - ./logger_service:/app
    networks:
      - kafka-test
    environment:
      POSTGRES_USER: micro_admin
      POSTGRES_PASSWORD: micro_pass
      POSTGRES_DB: perf_db

networks:
  kafka-test:
    driver: bridge
#    internal: true

volumes:
  perf_db:
  kafka_data:
